name: 'Eclipse to Makefile Converter'
description: 'Converts STM32CubeIDE/Eclipse CDT projects to a Makefile.'
author: 'ftobler'

branding:
  icon: 'play'
  color: 'purple'

inputs:
  project_path:
    description: 'Path to the STM32CubeIDE/Eclipse CDT project.'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.13'

    - name: Install eclipse-to-make
      run: pip install '${{ github.action_path }}/.'
      shell: bash

    - name: Install ARM GCC Toolchain (Linux)
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc-arm-none-eabi
      shell: bash

    - name: Install ARM GCC Toolchain (Windows)
      if: runner.os == 'Windows'
      run: choco install -y gcc-arm-embedded
      shell: bash

    - name: Install ARM GCC Toolchain (macOS)
      if: runner.os == 'macOS'
      run: brew install --cask gcc-arm-embedded
      shell: bash

    - name: Run eclipse-to-make
      run: cube_make ${{ inputs.project_path }}
      shell: bash
