import os
from typing import List
from cube_make.config import Config


tab = "\t"


class MakefileGenerator:
    def __init__(self, project_path: str, config: Config):
        self.project_path = project_path
        self.config = config

    def _get_optimization_flag(self) -> str:
        if self.config.optimization_level == "o0":
            return "-O0"
        elif self.config.optimization_level == "o1":
            return "-O1"
        elif self.config.optimization_level == "o2":
            return "-O2"
        elif self.config.optimization_level == "o3":
            return "-O3"
        elif self.config.optimization_level == "os":
            return "-Os"
        elif self.config.optimization_level == "ofast":
            return "-Ofast"
        else:
            return ""  # TODO either fail here or warn the user

    def _get_float_abi_flag(self) -> str:
        if self.config.float_abi == "hard":
            return "-mfloat-abi=hard"
        elif self.config.float_abi == "soft":
            return "-mfloat-abi=soft"
        else:
            return ""

    def _find_sources(self, extension: str) -> List[str]:
        found_files: List[str] = []
        for source_path in self.config.source_paths:
            full_path = os.path.join(self.project_path, source_path)
            for root, _, files in os.walk(full_path):
                for file in files:
                    if file.endswith(extension):
                        relative_path = os.path.relpath(os.path.join(root, file), self.project_path)
                        found_files.append(relative_path)
        # Sort files based on their directory structure to match the desired order
        # application, then Core/Src, then Drivers
        return sorted(found_files)

    def generate(self) -> str:
        c_sources = self._find_sources('.c')
        cpp_sources = self._find_sources('.cpp')
        s_sources = self._find_sources('.s')

        # Define source variables as space-separated lists

        c_sources_var = self.format_file_list("C_SOURCES", c_sources)
        cpp_sources_var = self.format_file_list("CPP_SOURCES", cpp_sources)
        s_sources_var = self.format_file_list("S_SOURCES", s_sources)

        # Collect all unique source directories for VPATH
        all_sources = c_sources + cpp_sources + s_sources
        vpath_dirs = sorted(list(set(os.path.dirname(src) for src in all_sources if os.path.dirname(src))))
        vpath_var = "VPATH = " + ":".join(vpath_dirs) if vpath_dirs else ""

        # Format include paths and defines with -I and -D prefixes
        c_includes_var = self.format_file_list("C_INCLUDES", self.config.include_paths, prefix="-I")
        c_defines_var = self.format_file_list("C_DEFINES", self.config.defines, prefix="-D")

        hex_conversion_raw = "$(OBJCOPY) -O ihex $(BUILD_DIR)/$(PROJECT_NAME).elf $(BUILD_DIR)/$(PROJECT_NAME).hex"
        bin_conversion_raw = "$(OBJCOPY) -O binary $(BUILD_DIR)/$(PROJECT_NAME).elf $(BUILD_DIR)/$(PROJECT_NAME).bin"

        if self.config.convert_hex:
            hex_conversion = f"{tab}{hex_conversion_raw}"
        else:
            hex_conversion = f"# {hex_conversion_raw}"

        if self.config.convert_bin:
            bin_conversion = f"{tab}{bin_conversion_raw}"
        else:
            bin_conversion = f"# {bin_conversion_raw}"

        opt_level_flag = self._get_optimization_flag()
        float_abi_flag = self._get_float_abi_flag()

        makefile_content = f"""
# Makefile generated by eclipse_to_make

PROJECT_NAME = {self.config.project_name}

# Source files
{c_sources_var}
{cpp_sources_var}
{s_sources_var}

# VPATH for source directories
{vpath_var}

# Include paths
{c_includes_var}

# Defines
{c_defines_var}

# Linker script
LD_SCRIPT = {self.config.linker_script}

# Toolchain
CC = arm-none-eabi-gcc
CXX = arm-none-eabi-g++
AS = arm-none-eabi-as
LD = arm-none-eabi-gcc
AR = arm-none-eabi-ar
OBJCOPY = arm-none-eabi-objcopy
OBJDUMP = arm-none-eabi-objdump
SIZE = arm-none-eabi-size

# Flags
OPT_LEVEL = {opt_level_flag}
FLOAT_ABI_FLAG = {float_abi_flag}
CPU_ARCH_FLAG = -mcpu={self.config.cpu_arch}
C_FLAGS = \
    $(CPU_ARCH_FLAG) \
    -std=gnu11 \
    -g3 \
    -ffunction-sections \
    -fdata-sections \
    -Wall \
    -fstack-usage \
    --specs=nano.specs \
    -mthumb \
    $(OPT_LEVEL) \
    $(FLOAT_ABI_FLAG)

CPP_FLAGS = \
    $(CPU_ARCH_FLAG) \
    -std=gnu++14 \
    -g3 \
    -ffunction-sections \
    -fdata-sections \
    -fno-exceptions \
    -fno-rtti \
    -fno-use-cxa-atexit \
    -Wall \
    -fstack-usage \
    --specs=nano.specs \
    -mthumb \
    $(OPT_LEVEL) \
    $(FLOAT_ABI_FLAG)

AS_FLAGS = \
    $(CPU_ARCH_FLAG) $(FLOAT_ABI_FLAG) -mthumb

LD_FLAGS = \
    -T$(LD_SCRIPT) \
    $(CPU_ARCH_FLAG) \
    --specs=nosys.specs \
    -Wl,--gc-sections \
    -static \
    --specs=nano.specs \
    -Wl,--start-group -lc -lm -lstdc++ -lsupc++ -Wl,--end-group \
    -mthumb $(OPT_LEVEL) $(FLOAT_ABI_FLAG)

# Output directories
BUILD_DIR = build

# Object files
C_OBJECTS = $(patsubst %.c,$(BUILD_DIR)/%.o,$(notdir $(C_SOURCES)))
CPP_OBJECTS = $(patsubst %.cpp,$(BUILD_DIR)/%.o,$(notdir $(CPP_SOURCES)))
S_OBJECTS = $(patsubst %.s,$(BUILD_DIR)/%.o,$(notdir $(S_SOURCES)))

OBJECTS = $(C_OBJECTS) $(CPP_OBJECTS) $(S_OBJECTS)

.PHONY: all clean

all: $(BUILD_DIR)/$(PROJECT_NAME).elf

$(BUILD_DIR)/$(PROJECT_NAME).elf: $(OBJECTS)
{tab}@mkdir -p $(@D)
# pre build step
{tab}{self.config.prebuild_step}
{tab}$(LD) $(LD_FLAGS) $(OBJECTS) -o $@
{tab}$(SIZE) $@
# *.hex conversion
{hex_conversion}
# *.bin conversion
{bin_conversion}
# post build step
{tab}{self.config.postbuild_step}

# all targets for C (*.c) files
$(BUILD_DIR)/%.o: %.c
{tab}@mkdir -p $(@D)
{tab}$(CC) $(C_FLAGS) $(C_INCLUDES) $(C_DEFINES) -c $< -o $@

# all targets for C++ (*.cpp) files
$(BUILD_DIR)/%.o: %.cpp
{tab}@mkdir -p $(@D)
{tab}$(CXX) $(CPP_FLAGS) $(C_INCLUDES) $(C_DEFINES) -c $< -o $@

# all targets for assembly (*.s) files
$(BUILD_DIR)/%.o: %.s
{tab}@mkdir -p $(@D)
{tab}$(AS) $(AS_FLAGS) $< -o $@

clean:
{tab}rm -rf $(BUILD_DIR)

"""
        return makefile_content

    def format_file_list(self, key: str, file_list: List[str], prefix: str = "") -> str:
        backdash = "\\"
        newline = "\n"
        if len(file_list) == 0:
            return f"# {key} = <list is empty>"
        formatted_list = [f"{prefix}{item}" for item in file_list]
        return f"{key} = " + (f" {backdash}{newline}{tab}".join([""] + formatted_list))
